### 1. Đăng ký tài khoản mới
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "nghia26",
  "email": "nghia26@example.com",
  "password": "123456"
}

### 2. Đăng nhập (lấy AccessToken + RefreshToken)
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "usernameOrEmail": "nghia26",
  "password": "654321"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### 3. Gọi API cần authentication (test access token)
GET http://localhost:8080/api/users/me
Authorization: Bearer {{accessToken}}

### 4. Refresh token (lấy access token mới)
POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### 5. Đổi mật khẩu
POST http://localhost:8080/api/auth/change-password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{

  "oldPassword": "123456",
  "newPassword": "654321"
}

### 6. Đăng nhập lại bằng mật khẩu mới
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "usernameOrEmail": "nghia26",
  "password": "654321"
}
